export const dataBarang = [
  {
    id: 1,
    kode_barang: "GMI-555-BALL",
    nama_barang: "GMI-555-BALL",
    merk: "123-TIPE",
    jenis_barang: "Ball-Joint",
    gudang: "taman_sari",
    total_stok: 100,
  },
  {
    id: 2,
    kode_barang: "TYP-745-HEX",
    nama_barang: "TYP-745-HEX",
    merk: "XYZ-TYPE",
    jenis_barang: "Hex-Bolt",
    gudang: "kembang_sari",
    total_stok: 150,
  },
  {
    id: 3,
    kode_barang: "BMW-234-VALVE",
    nama_barang: "BMW-234-VALVE",
    merk: "BMW-TYPE",
    jenis_barang: "Valve",
    gudang: "surya_gudang",
    total_stok: 200,
  },
  {
    id: 4,
    kode_barang: "GMI-344-NUT",
    nama_barang: "GMI-344-NUT",
    merk: "GMI-TYPE",
    jenis_barang: "Nut",
    gudang: "sejahtera",
    total_stok: 500,
  },
  {
    id: 5,
    kode_barang: "TYP-982-BRACKET",
    nama_barang: "TYP-982-BRACKET",
    merk: "XYZ-TYPE",
    jenis_barang: "Bracket",
    gudang: "kembang_sari",
    total_stok: 80,
  },
  {
    id: 6,
    kode_barang: "SIL-563-WASHER",
    nama_barang: "SIL-563-WASHER",
    merk: "SIL-TYPE",
    jenis_barang: "Washer",
    gudang: "surya_gudang",
    total_stok: 300,
  },
  {
    id: 7,
    kode_barang: "GMI-123-BUSHING",
    nama_barang: "GMI-123-BUSHING",
    merk: "GMI-TYPE",
    jenis_barang: "Bushing",
    gudang: "taman_sari",
    total_stok: 120,
  },
  {
    id: 8,
    kode_barang: "BRK-759-SPACER",
    nama_barang: "BRK-759-SPACER",
    merk: "BRK-TYPE",
    jenis_barang: "Spacer",
    gudang: "sejahtera",
    total_stok: 90,
  },
  {
    id: 9,
    kode_barang: "HDX-234-PIN",
    nama_barang: "HDX-234-PIN",
    merk: "HDX-TYPE",
    jenis_barang: "Pin",
    gudang: "surya_gudang",
    total_stok: 400,
  },
  {
    id: 10,
    kode_barang: "PQR-678-SHAFT",
    nama_barang: "PQR-678-SHAFT",
    merk: "PQR-TYPE",
    jenis_barang: "Shaft",
    gudang: "taman_sari",
    total_stok: 50,
  },
];

export const dataLokasi = [
  {
    id: 1,
    namaLokasi: "GMI-777-PACK",
    gudang: "GMI-777-PACK",
    jenis: "TMS-L3-P-B001",
    volume: "600 PCS",
    deskripsi: "PCS",
  },
  {
    id: 2,
    namaLokasi: "GMI-890-UNIT",
    gudang: "GMI-890-UNIT",
    jenis: "TMS-L1-R-B002",
    volume: "1000 PCS",
    deskripsi: "PCS",
  },
];
